In [3]:
import os
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

# 커널을 구성하다보면 에러는 아니지만, 빨간색 네모 박스 warning이 뜨는 경우를 제거 
import warnings
warnings.filterwarnings('ignore')

## 데이터 로드

In [5]:
# define path
path = 'D:/ㄱ머신러닝 스터디/JobCare/'

In [6]:
train = pd.read_csv(path + 'train.csv')
test = pd.read_csv(path + 'test.csv')
submission = pd.read_csv(path + 'sample_submission.csv')

## EDA

In [7]:
# shape of the data
print(train.shape)
print(test.shape)
print(submission.shape)

(501951, 35)
(46404, 34)
(46404, 2)

In [8]:
# summary
train.info()

# 대부분의 데이터는 정수로 이뤄져 있고 non-null count 열을 보니
# 결측치는 없는 것으로 보임

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501951 entries, 0 to 501950
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      501951 non-null  int64
 1   d_l_match_yn            501951 non-null  bool
 2   d_m_match_yn            501951 non-null  bool
 3   d_s_match_yn            501951 non-null  bool
 4   h_l_match_yn            501951 non-null  bool
 5   h_m_match_yn            501951 non-null  bool
 6   h_s_match_yn            501951 non-null  bool
 7   person_attribute_a      501951 non-null  int64
 8   person_attribute_a_1    501951 non-null  int64
 9   person_attribute_b      501951 non-null  int64
 10  person_prefer_c         501951 non-null  int64
 11  person_prefer_d_1       501951 non-null  int64
 12  person_prefer_d_2       501951 non-null  int64
 13  person_prefer_d_3       501951 non-null  int64
 14  person_prefer_e         501951 non-null  int64
 15  person_prefer_f         501951 non-null  int64
 16  person_prefer_g         501951 non-null  int64
 17  person_prefer_h_1       501951 non-null  int64
 18  person_prefer_h_2       501951 non-null  int64
 19  person_prefer_h_3       501951 non-null  int64
 20  contents_attribute_i    501951 non-null  int64
 21  contents_attribute_a    501951 non-null  int64
 22  contents_attribute_j_1  501951 non-null  int64
 23  contents_attribute_j    501951 non-null  int64
 24  contents_attribute_c    501951 non-null  int64
 25  contents_attribute_k    501951 non-null  int64
 26  contents_attribute_l    501951 non-null  int64
 27  contents_attribute_d    501951 non-null  int64
 28  contents_attribute_m    501951 non-null  int64
 29  contents_attribute_e    501951 non-null  int64
 30  contents_attribute_h    501951 non-null  int64
 31  person_rn               501951 non-null  int64
 32  contents_rn             501951 non-null  int64
 33  contents_open_dt        501951 non-null  object
 34  target                  501951 non-null  int64
dtypes: bool(6), int64(28), object(1)
memory usage: 113.9+ MB

In [9]:
train.describe(include = 'O')
# 오브젝트 데이터인 contents_open_dt는 컨텐츠 연 날짜 시간임

           contents_open_dt
count                501951
unique               494952
top     2020-02-18 12:42:30
freq                      4

In [10]:
cols = train.columns.values.tolist()
cols

['id',
 'd_l_match_yn',
 'd_m_match_yn',
 'd_s_match_yn',
 'h_l_match_yn',
 'h_m_match_yn',
 'h_s_match_yn',
 'person_attribute_a',
 'person_attribute_a_1',
 'person_attribute_b',
 'person_prefer_c',
 'person_prefer_d_1',
 'person_prefer_d_2',
 'person_prefer_d_3',
 'person_prefer_e',
 'person_prefer_f',
 'person_prefer_g',
 'person_prefer_h_1',
 'person_prefer_h_2',
 'person_prefer_h_3',
 'contents_attribute_i',
 'contents_attribute_a',
 'contents_attribute_j_1',
 'contents_attribute_j',
 'contents_attribute_c',
 'contents_attribute_k',
 'contents_attribute_l',
 'contents_attribute_d',
 'contents_attribute_m',
 'contents_attribute_e',
 'contents_attribute_h',
 'person_rn',
 'contents_rn',
 'contents_open_dt',
 'target']

In [11]:
# 속성 D, H, L 제외한 속성 및 컨텐츠 사용 날짜 등 삭제
train_rev = train[['id',
 'd_l_match_yn',
 'd_m_match_yn',
 'd_s_match_yn',
 'h_l_match_yn',
 'h_m_match_yn',
 'h_s_match_yn',
#  'person_attribute_a',
#  'person_attribute_a_1',
#  'person_attribute_b',
#  'person_prefer_c',
 'person_prefer_d_1',
 'person_prefer_d_2',
 'person_prefer_d_3',
#  'person_prefer_e',
#  'person_prefer_f',
#  'person_prefer_g',
 'person_prefer_h_1',
 'person_prefer_h_2',
 'person_prefer_h_3',
#  'contents_attribute_i',
#  'contents_attribute_a',
#  'contents_attribute_j_1',
#  'contents_attribute_j',
#  'contents_attribute_c',
#  'contents_attribute_k',
 'contents_attribute_l',
 'contents_attribute_d',
#  'contents_attribute_m',
#  'contents_attribute_e',
 'contents_attribute_h',
 'person_rn',
 'contents_rn',
 'contents_open_dt',
 'target']]

In [12]:
train_rev.head()

,id,d_l_match_yn,d_m_match_yn,d_s_match_yn,h_l_match_yn,h_m_match_yn,h_s_match_yn,person_prefer_d_1,person_prefer_d_2,person_prefer_d_3,person_prefer_h_1,person_prefer_h_2,person_prefer_h_3,contents_attribute_l,contents_attribute_d,contents_attribute_h,person_rn,contents_rn,contents_open_dt,target
0,0,True,True,True,False,False,False,275,370,369,4,95,59,1608,275,139,618822,354805,2020-01-17 12:09:36,1
1,1,False,False,False,True,True,False,114,181,175,131,101,96,1608,275,133,571659,346213,2020-06-18 17:48:52,0
2,2,False,False,False,True,False,False,464,175,452,54,263,56,1600,94,53,399816,206408,2020-07-08 20:00:10,0
3,3,False,False,False,True,False,False,703,705,704,72,227,2,1608,275,74,827967,572323,2020-01-13 18:09:34,0
4,4,True,True,True,False,False,False,275,370,369,214,210,209,1608,275,74,831614,573899,2020-03-09 20:39:22,0